//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Inventory_System_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BillingDBEntities : DbContext
    {
        public BillingDBEntities()
            : base("name=BillingDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcustomer> tblcustomers { get; set; }
        public virtual DbSet<tblinvice_details> tblinvice_details { get; set; }
        public virtual DbSet<tblinvice_payments> tblinvice_payments { get; set; }
        public virtual DbSet<tblinvice_products> tblinvice_products { get; set; }
        public virtual DbSet<tblproduct> tblproducts { get; set; }
    }
}
