//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Inventory_System_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvice_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblinvice_details()
        {
            this.tblinvice_products = new HashSet<tblinvice_products>();
            this.tblinvice_payments = new HashSet<tblinvice_payments>();
        }
    
        public int Invice_id { get; set; }
        public Nullable<int> Customer_id { get; set; }
        public Nullable<System.DateTime> Invice_date { get; set; }
        public int Invice_number { get; set; }
        public Nullable<double> Total_ammount { get; set; }
    
        public virtual tblcustomer tblcustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvice_products> tblinvice_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblinvice_payments> tblinvice_payments { get; set; }
    }
}
