//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Inventory_System_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvice_products
    {
        public int Invice_Product_id { get; set; }
        public Nullable<int> Invice_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<double> Quantity { get; set; }
    
        public virtual tblinvice_details tblinvice_details { get; set; }
        public virtual tblproduct tblproduct { get; set; }
    }
}
