//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Inventory_System_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvice_payments
    {
        public int Payment_id { get; set; }
        public Nullable<int> Invice_id { get; set; }
        public Nullable<System.DateTime> Payment_date { get; set; }
        public Nullable<double> Payment_ammount { get; set; }
        public string Payment_mode { get; set; }
        public string Description { get; set; }
    
        public virtual tblinvice_details tblinvice_details { get; set; }
    }
}
